"""Rule storage, dedupe, scope matching, resolution and Copilot instruction sync."""
from __future__ import annotations

import difflib
import functools
import hashlib
import re
from pathlib import Path

import store
from mapper import section_of

SIMILARITY = 0.92  # high on purpose: a wrong merge silently loses a rule, a missed duplicate is only clutter
GENERATED_MARKER = "<!-- generated by lore; edit rules with review.py, not this file -->"


# ---------- scopes ----------

def split_globs(value: str) -> list[str]:
    """Split on commas that are not inside {braces}."""
    out, depth, cur = [], 0, ""
    for ch in value:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth = max(0, depth - 1)
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    out.append(cur.strip())
    return [g.strip("'\"") for g in out if g]


def parse_scope(spec: str) -> dict:
    spec = (spec or "global").strip()
    if spec == "global":
        return {"type": "global"}
    kind, _, val = spec.partition(":")
    if kind == "section" and val.strip():
        return {"type": "section", "value": val.strip().strip("/")}
    if kind == "glob" and val.strip():
        return {"type": "glob", "globs": split_globs(val)}
    raise ValueError(f"bad scope {spec!r}: use global, section:<name> or glob:<pattern,...>")


def scope_key(scope: dict) -> str:
    if scope["type"] == "global":
        return "global"
    if scope["type"] == "section":
        return f"section:{scope['value']}"
    return "glob:" + ",".join(scope["globs"])


def _expand_braces(p: str) -> list[str]:
    m = re.search(r"\{([^{}]*)\}", p)
    if not m:
        return [p]
    return [r for alt in m.group(1).split(",")
            for r in _expand_braces(p[:m.start()] + alt + p[m.end():])]


@functools.lru_cache(maxsize=512)
def _glob_regexes(pattern: str) -> tuple:
    res = []
    for p in _expand_braces(pattern):
        if p.startswith("./"):
            p = p[2:]
        if "/" not in p:
            p = "**/" + p
        out, i = "", 0
        while i < len(p):
            if p.startswith("**/", i):
                out += "(?:.*/)?"; i += 3
            elif p.startswith("**", i):
                out += ".*"; i += 2
            elif p[i] == "*":
                out += "[^/]*"; i += 1
            elif p[i] == "?":
                out += "[^/]"; i += 1
            else:
                out += re.escape(p[i]); i += 1
        res.append(re.compile("^" + out + "$"))
    return tuple(res)


def glob_match(pattern: str, rel: str) -> bool:
    return any(r.match(rel) for r in _glob_regexes(pattern))


def section_matches(rule_value: str, sec: str) -> bool:
    v = rule_value.strip("/")
    return sec == v or sec.endswith("/" + v) or sec.startswith(v + "/")


def rule_applies(rule: dict, rel: str) -> str | None:
    """Return 'file' | 'section' | 'global' if the rule applies to rel, else None."""
    sc = rule["scope"]
    if sc["type"] == "global":
        return "global"
    if sc["type"] == "section":
        return "section" if section_matches(sc["value"], section_of(rel)) else None
    return "file" if any(glob_match(g, rel) for g in sc["globs"]) else None


# ---------- storage ----------

def _path(name: str) -> Path:
    return store.project_dir(name) / "rules.json"


def load(name: str) -> list[dict]:
    return store.load_json(_path(name), {"version": 1, "rules": []})["rules"]


def save(name: str, rules: list[dict]) -> None:
    store.save_json(_path(name), {"version": 1, "rules": rules})


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[^a-z0-9 ]", " ", text.lower())).strip()


def _rule_id(text: str, scope: dict) -> str:
    return hashlib.sha1((_norm(text) + "|" + scope_key(scope)).encode()).hexdigest()[:8]


def add_rule(name: str, text: str, scope: dict, status: str = "pending",
             source: str = "manual", evidence: str = "") -> tuple[dict, str]:
    """Add a rule. Returns (rule, outcome) with outcome in added|duplicate|promoted."""
    text = " ".join(text.split())
    if not text:
        raise ValueError("empty rule")
    rules = load(name)
    key, ntext = scope_key(scope), _norm(text)
    for r in rules:
        if scope_key(r["scope"]) != key:
            continue
        if difflib.SequenceMatcher(None, _norm(r["text"]), ntext).ratio() >= SIMILARITY:
            r["hits"] = r.get("hits", 0) + 1
            outcome = "duplicate"
            if r["status"] == "pending" and status == "active":
                r["status"], outcome = "active", "promoted"
            save(name, rules)
            return r, outcome
    rule = {
        "id": _rule_id(text, scope), "text": text, "scope": scope, "status": status,
        "source": source, "evidence": evidence, "created": store.now(), "hits": 0,
    }
    rules.append(rule)
    save(name, rules)
    return rule, "added"


def edit_rule(name: str, rule_id: str, text: str | None = None, scope: dict | None = None) -> dict:
    """Change a rule's text and/or scope in place (its id and status are kept)."""
    rules = load(name)
    rule = next((r for r in rules if r["id"] == rule_id), None)
    if rule is None:
        raise KeyError(rule_id)
    new_text = " ".join(text.split()) if text is not None else rule["text"]
    if not new_text:
        raise ValueError("empty rule")
    new_scope = scope if scope is not None else rule["scope"]
    key, ntext = scope_key(new_scope), _norm(new_text)
    for other in rules:
        if other is not rule and scope_key(other["scope"]) == key \
                and difflib.SequenceMatcher(None, _norm(other["text"]), ntext).ratio() >= SIMILARITY:
            raise ValueError(f"duplicate of rule {other['id']}")
    rule["text"], rule["scope"], rule["edited"] = new_text, new_scope, store.now()
    save(name, rules)
    return rule


def set_status(name: str, ids: list[str], status: str | None) -> list[dict]:
    """status=None removes the rules. Returns affected rules."""
    rules = load(name)
    hit = [r for r in rules if r["id"] in ids]
    if status is None:
        rules = [r for r in rules if r["id"] not in ids]
    else:
        for r in hit:
            r["status"] = status
    save(name, rules)
    return hit


# ---------- resolution ----------

def _tokens(s: str) -> int:
    return max(1, len(s) // 4)


def resolve(name: str, rel_paths: list[str], max_tokens: int = 800) -> dict:
    """Pick the active rules relevant to rel_paths, most specific first, within a budget."""
    rel_paths = [p.strip("/") for p in rel_paths if p]
    rules = [r for r in load(name) if r["status"] == "active"]
    picked: dict[str, tuple[int, dict, str]] = {}
    order = {"file": 0, "section": 1, "global": 2}
    for rel in rel_paths:
        for r in rules:
            lvl = rule_applies(r, rel)
            if lvl and (r["id"] not in picked or order[lvl] < picked[r["id"]][0]):
                picked[r["id"]] = (order[lvl], r, lvl)
    ranked = sorted(picked.values(), key=lambda t: (t[0], t[1]["created"]))

    secs = sorted({section_of(p) for p in rel_paths})
    header = f"Rules for project `{name}` (follow before writing code; sections: {', '.join(secs) or '-'})"
    used, shown, omitted = _tokens(header), [], 0
    for _, r, lvl in ranked:
        line = f"- [{lvl}] {r['text']}"
        if used + _tokens(line) > max_tokens:
            omitted += 1
            continue
        used += _tokens(line)
        shown.append((r, lvl, line))

    text = header + "\n" + "\n".join(l for _, _, l in shown) if shown else ""
    if omitted:
        text += f"\n(+{omitted} more rules omitted by the {max_tokens}-token budget)"
    return {"sections": secs, "rules": [r for r, _, _ in shown], "omitted": omitted, "text": text}


# ---------- Copilot instruction files (static fallback) ----------

def is_generated(text: str) -> bool:
    return GENERATED_MARKER in text[:800]


def sync_copilot(name: str, root: Path) -> list[str]:
    """Write active rules to <root>/.github/instructions/lore-*.instructions.md."""
    amap = store.load_json(store.project_dir(name) / "map.json", {"sections": {}})
    groups: dict[str, tuple[str, list[str]]] = {}  # file slug -> (applyTo, [texts])
    skipped = []
    for r in load(name):
        if r["status"] != "active":
            continue
        sc = r["scope"]
        if sc["type"] == "global":
            slug, apply_to = "global", "**"
        elif sc["type"] == "section":
            hits = [s for s in amap["sections"] if section_matches(sc["value"], s)]
            if not hits:
                skipped.append(r["id"])
                continue
            paths = [amap["sections"][s]["path"] for s in hits]
            slug = "section-" + re.sub(r"[^A-Za-z0-9]+", "-", sc["value"]).strip("-")
            apply_to = ",".join("**" if not p else f"{p}/**" for p in paths)
        else:
            apply_to = ",".join(sc["globs"])
            slug = "glob-" + hashlib.sha1(apply_to.encode()).hexdigest()[:6]
        groups.setdefault(slug, (apply_to, []))[1].append(r["text"])

    outdir = root / ".github" / "instructions"
    outdir.mkdir(parents=True, exist_ok=True)
    written = []
    for slug, (apply_to, texts) in sorted(groups.items()):
        fp = outdir / f"lore-{slug}.instructions.md"
        body = "\n".join(f"- {t}" for t in texts)
        fp.write_text(f'---\napplyTo: "{apply_to}"\n---\n{GENERATED_MARKER}\n\n{body}\n', encoding="utf-8")
        written.append(str(fp))
    for old in outdir.glob("lore-*.instructions.md"):  # prune stale generated files
        if str(old) not in written and is_generated(old.read_text(encoding="utf-8", errors="replace")):
            old.unlink()
    if skipped:
        print(f"warning: {len(skipped)} section rule(s) skipped: section not in map (re-run memorize.py)")
    return written
