"""Static fallback for clients without MCP: write active rules as Copilot instruction files."""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from . import textutil
from .models import ScopeKind, Status
from .projects import Project
from .repository import RuleRepository

GENERATED_MARKER = "<!-- generated by lore; edit rules with review.py, not this file -->"


def is_generated(text: str) -> bool:
    """True for files this module wrote (so they are never re-imported as rules)."""
    return GENERATED_MARKER in text[:800]


@dataclass
class SyncResult:
    written: list[Path] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)   # ids of section rules whose section is not in the map


def sync_copilot(project: Project) -> SyncResult:
    """Write active rules to <root>/.github/instructions/lore-*.instructions.md, grouped by scope."""
    sections = project.load_map()["sections"]
    groups: dict[str, tuple[str, list[str]]] = {}   # file slug -> (applyTo, [rule texts])
    result = SyncResult()
    for rule in RuleRepository(project.name).with_status(Status.ACTIVE):
        scope = rule.scope
        if scope.kind is ScopeKind.GLOBAL:
            slug, apply_to = "global", "**"
        elif scope.kind is ScopeKind.SECTION:
            hits = [s for s in sections if scope.covers_section(s)]
            if not hits:
                result.skipped.append(rule.id)
                continue
            paths = [sections[s]["path"] for s in hits]
            slug = "section-" + re.sub(r"[^A-Za-z0-9]+", "-", scope.section).strip("-")
            apply_to = ",".join("**" if not p else f"{p}/**" for p in paths)
        else:
            apply_to = ",".join(scope.globs)
            slug = "glob-" + textutil.short_hash(apply_to, 6)
        groups.setdefault(slug, (apply_to, []))[1].append(rule.text)

    outdir = project.root / ".github" / "instructions"
    outdir.mkdir(parents=True, exist_ok=True)
    for slug, (apply_to, texts) in sorted(groups.items()):
        fp = outdir / f"lore-{slug}.instructions.md"
        body = "\n".join(f"- {t}" for t in texts)
        fp.write_text(f'---\napplyTo: "{apply_to}"\n---\n{GENERATED_MARKER}\n\n{body}\n', encoding="utf-8")
        result.written.append(fp)
    for old in outdir.glob("lore-*.instructions.md"):   # prune stale generated files
        if old not in result.written and is_generated(old.read_text(encoding="utf-8", errors="replace")):
            old.unlink()
    return result
